routes/web.php
<?php

/*Route::group(['middleware' => 'web'], function() {
  Route::group(['namespace' => 'Frontend'], function () {
    require (__DIR__ . '/Routes/Frontend/Access.php');
  });
});*/

require (__DIR__ . '/web/validador_documento/validador_documento.php');
require (__DIR__ . '/web/texto_doc_electronicos/texto_doc_electronicos.php');
require (__DIR__ . '/web/colaboracion/colaboracion.php');




Auth::routes();


Route::get('/', function () {
    return view('auth.login');
})->middleware('guest');


Route::group(['middleware' => ['admin']], function() {

//Route::any('/claveunica/autenticar', 'Auth\LoginController@redirectToProvider')->name('login.claveunica');
//Route::any('/claveunica/validar', 'Auth\LoginController@handleProviderCallback')->name('login.claveunica.callback');

  /* INICIO */
  require (__DIR__ . '/web/inicio/inicio.php');
  /* FIN INICIO */

  /* OPA */
  require (__DIR__ . '/web/opa/opa.php');
  /* FIN OPA */

  /* buscador global */
  require (__DIR__ . '/web/buscador_global/buscador_global.php');
  /* FIN buscador global */

  /* HISTORICO GD */
  require (__DIR__ . '/web/historico_gd/historico_gd.php');
  /* FIN HISTORICO GD  */

  /* LEY */
  require (__DIR__ . '/web/ley/ley.php');
  /* FIN LEY */

  /* SEGURIDAD */
    require (__DIR__ . '/web/seguridad/seguridad.php');
  /* FIN SEGURIDAD */

    /* TRAZABILIDAD (DERIVACION TRAMITES) */
    require (__DIR__ . '/web/trazabilidad/trazabilidad.php');
  /* FIN TRAZABILIDAD */

    /* TRAMITES (DERIVACION TRAMITES) */
    require (__DIR__ . '/web/tramites/tramites.php');
  /* FIN TRAZABILIDAD */

    /* TRAMITES (XML) */
    require (__DIR__ . '/web/xmlapdf/xmlapdf.php');
    /* TRAMITES (XML) */

    /* TRAMITES (COMPRAS) */
    require (__DIR__ . '/web/requerimientos_compras/requerimientos_compras.php');
    /* TRAMITES (COMPRAS) */

    /* TRAMITES (TRASLADOS) */
    require (__DIR__ . '/web/traslados/traslados.php');
    /* TRAMITES (TRASLADOS) */

    /* TRAMITES (TICKETS) */
    require (__DIR__ . '/web/tickets/tickets.php');
    /* TRAMITES (TICKETS) */

  /* RECONOCIMIENTO */
  require (__DIR__ . '/web/reconocimiento/reconocimiento.php');
  /* RECONOCIMIENTO */

  /* SIAC */
  require (__DIR__ . '/web/siac/siac.php');
  /* SIAC */

  /* CEVS */
  require (__DIR__ . '/web/cevs/cevs.php');
  /* CEVS */

  /* PATROCINIO */
  require (__DIR__ . '/web/patrocinio/patrocinio.php');
  /* PATROCINIO */

  /* RECLAMOS */
  require (__DIR__ . '/web/reclamos/reclamos.php');
  /* RECLAMOS */

  /* PROTOCOLO */
  require (__DIR__ . '/web/protocolo/protocolo.php');
  /* PROTOCOLO */

   /* TRAMITES (DERIVACION TRAMITES) */
    require (__DIR__ . '/web/memos/memos.php');
  /* FIN TRAZABILIDAD */

  /* TRAMITES (DERIVACION TRAMITES) */
    require (__DIR__ . '/web/resolucionexenta/resolucionexenta.php');
  /* FIN TRAZABILIDAD */



  /* TRAMITES (DERIVACION TRAMITES) */
    require (__DIR__ . '/web/oficio/oficio.php');
  /* FIN TRAZABILIDAD */


 /* INICIO */
  require (__DIR__ . '/web/firmar_documentos/firmar_documentos.php');
  /* FIN INICIO */


  /* PERFIL DE USUARIO */
    require (__DIR__ . '/web/perfil_usuario/perfil_usuario.php');
  /* FIN PERFIL DE USUARIOS */


  /* TRAMITES (SIGC) */
    require (__DIR__ . '/web/sigc/sigc.php');
  /* FIN SIGC */


  /* TRAMITES (Transparencia) */
   require (__DIR__ . '/web/transparencia/transparencia.php');
  /* FIN Transparencia */


  /* TRAMITES (integridad) */
  require (__DIR__ . '/web/integridad/integridad.php');
  /* FIN integridad */


   /* TRAMITES (beneficios) */
   require (__DIR__ . '/web/beneficios/maternidad.php');
   require (__DIR__ . '/web/beneficios/escolaridad.php');
   /* FIN beneficios */

   /* TRAMITES (Incentivo Retiro) */
   require (__DIR__ . '/web/incentivo_retiro/incentivo_retiro.php');
   /* FIN Incentivo Retiro */

    /* DOC DIGITALES*/
    require (__DIR__ . '/web/documentos_digitales/documentos_digitales.php');
    /* FIN DOC DIGITALES */

    /* GESTIÓN DOCUMENTAL*/
    require (__DIR__ . '/web/derivacion_documental/derivacion_documental.php');
    /* FIN GESTIÓN DOCUMENTAL */

    /* VIAJES PARLAMENTARIOS*/
    require (__DIR__ . '/web/parlamentarios/parlamentarios.php');
    /* FIN VIAJES PARLAMENTARIOS */

    /* Agenda Seremis*/
    require (__DIR__ . '/web/agendaseremis/agendaseremis.php');
    /* FIN Agenda Seremis */
    

  /* ROUTE ERROR */
  Route::get('500', function() {abort(500);});
  /* FIN ROUTE ERROR */
});

app/Models/Oficio/Oficio.php
<?php

namespace App\Models\Oficio;

use Illuminate\Database\Eloquent\Model;
use  App\Models\OficioColaboracion\OficioColaboracion;
use  App\Models\CorrelativoDocumentoUnidad\CorrelativoDocumentoUnidad;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\UsuariosSimple\UsuariosSimple;

class Oficio extends Model
{
	use SoftDeletes;

    protected $table =  'oficio';

    protected $fillable = ['id', 'tramite_id' , 'division' , 'lugar' , 'correlativo', 'categoria', 'fecha' , 'fecha_folio', 'remitente' , 'destinatario', 'desde' , 'antecedentes', 'materia', 'contenido' , 'vistos_responsabilidad' , 'distribucion' , 'doc_anexo_a' , 'doc_anexo_b' , 'doc_anexo_c' , 'doc_oficio', 'deleted_at', 'documento_distribuido'];

    protected $primarykey = 'id';

    public $timestamps = true;


    public function getEstatusAttribute()
	{
		if($this->doc_oficio!=null && $this->doc_oficio!=" "){
	    	return 'Completado';
		}else{
			return 'Incompleto';
		}
	}

	public function colaboraciones()
	{
      return $this->hasMany(OficioColaboracion::class, 'tramite_id', 'tramite_id');
    }
    public function correlativo()
	{
		$relacion = $this->belongsTo(CorrelativoDocumentoUnidad::class, 'tramite_id', 'tramite_documento_id');
		if($relacion){
			return $relacion;
			}
			else{
				return '';
			}

	    //return $this->belongsTo(CorrelativoDocumentoUnidad::class, 'tramite_id', 'tramite_documento_id');
	}

	public function getEmailRemitenteAttribute()
	{
		$email = UsuariosSimple::where('nombre_cargo',$this->remitente)->first();
		return $email;

	}

}

app/Http/Controllers/Oficios/OficiosColaboracionesController.php
<?php

namespace App\Http\Controllers\Oficios;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use GuzzleHttp\Client;
use App\Models\DerivacionesDocumento\DerivacionesDocumento;
use App\Models\IngresoTramite\IngresoTramite;
use Carbon\Carbon;
use Maatwebsite\Excel\Facades\Excel;
use App\Imports\ComboBoxCompra;
use App\Models\TiposDocumentos\TiposDocumentos;
use App\Models\Divisiones\Divisiones;
use App\Models\Oficio\Oficio;
use App\Models\OficioColaboracion\OficioColaboracion;
use DB;
use App\Models\File\File;
use Illuminate\Support\Facades\Auth;
use App\Models\UsuariosSimple\UsuariosSimple;


class OficiosColaboracionesController extends Controller
{
   public function index(Request $request){

      set_time_limit(14200);
      $selectA = Divisiones::get()->pluck('nombre', 'nombre')->prepend('Todos', null);
      $requestNRegistro = null;
      $listado = [];
      $anno = Carbon::now()->format('Y');
      $fechaStringInicio = ($anno).'-01-01 00:00:00';
      $feDesde = Carbon::parse($fechaStringInicio);
      $feHasta =  Carbon::parse(Carbon::now()->format('Y-m-d').' 23:59:59');
      $fechaInDesde = Carbon::parse($fechaStringInicio);
      $fechaInHasta = Carbon::now();
      $fechas[1] = Date('Y-m-d', strtotime( '1970-01-01' ));
      $fechas[0] = Date('Y-m-d', strtotime(Carbon::now()->format('Y-m-d')));
      $areRemitenteView = '';
      $remitenteView = '';
      $materiaView = '';
      $destinatarioView = '';
      $correlativoView = '';
      $divisionusuarios = Auth::user()->department;
      $divisiondestinatario = Auth::user()->department;
      $reservado = 'reservado';
      $esAdmin = false;
      $listadoNoreservado = collect([]);


          if( $request->FechaDesde != null ) {
            $feDesde=(Carbon::parse($request->get('FechaDesde'))->format('dmY'));
            $feDesde= Carbon::parse(substr($feDesde, 0, 2).'-'.substr($feDesde, 2, 2).'-'.substr($feDesde, 4, 4).' 00:00:00');
          }
          if( $request->FechaHasta != null ) {
             $feHasta=(Carbon::parse($request->get('FechaHasta'))->format('dmY'));
             $feHasta= Carbon::parse(substr($feHasta, 0, 2).'-'.substr($feHasta, 2, 2).'-'.substr($feHasta, 4, 4).' 23:59:59');
          }



      $query = Oficio::query ();
      $query->when(request('nRegistro', false), function ($q, $numRegistro) { 
            return $q->where('tramite_id', $numRegistro);
        });
      $query->when(request('remitente'), function ($q, $remitente) { 
            return $q->where('remitente', 'LIKE', "%$remitente%");
        });
      $query->when(request('materia'), function ($q, $materia) { 
            return $q->where('materia', 'LIKE', "%$materia%");
        });
      $query->when(request('destinatario'), function ($q, $destinatario) { 
            return $q->where('destinatario', 'LIKE', "%$destinatario%");
        });
      $query->when($feDesde, function ($q, $feDesde ) { 
            return $q->where('created_at','>=', $feDesde);
        });
      $query->when($feHasta, function ($q, $feHasta ) { 
            return $q->where('created_at','<=', $feHasta);
        });

      foreach (auth()->user()->roles as $role) {
            if ($role->todos == 1) {
                $esAdmin=  true;
                break;
            }
        }
      /*if(!$esAdmin){

      $query->when(request('areaRemtiente', false), function ($q, $areaRemtiente) { 
            return $q->where('division', $areaRemtiente);
        });
      $query->when($divisionusuarios, function ($q, $divisionusuarios) { 
            return $q->where('division', $divisionusuarios);
        });
      $query->when($divisiondestinatario, function ($q, $divisiondestinatario) { 
            return $q->orwhere('division_destinatario', $divisiondestinatario);
        });
      $query->when($reservado, function ($q, $reservado ) { 
              return $q->where('reservado', 0);
          });

    }*/

     $listado = $query->get()->sortByDesc(function($q){
     return $q->correlativo->correlativo;
     });

      foreach ($listado as $clave => $reg) {
                
         $reg->materia = str_replace('"Times New Roman",serif', ' ', $reg->materia);
         $reg->materia = str_replace('"Arial",sans-serif', ' ', $reg->materia);
      }
      if($request->correlativo != null ) {
      
      $correlativoView = (int)$request->correlativo;
      foreach ($listado as $clave => $reg) {

       if($reg->correlativo != ''){
        if($reg->correlativo->correlativo === $correlativoView)
        $listado = [$reg];    
      }
      }
      }
      /*if(!$esAdmin){
      foreach ($listado as $clave => $reg) {

        if($reg->reservado == 0)
        $listadoNoreservado->push($reg);    
      }
      $listado = $listadoNoreservado;
      }

      $emailUsuarioSesion = auth()->user()->email;
      $nombrecargosimple = UsuariosSimple::where('email',$emailUsuarioSesion)->first()->nombre_cargo;
      $listado2 = Oficio::where('remitente', $nombrecargosimple )->where('reservado', 1)->get();
      foreach ($listado2 as $key => $value) {
        $listado->push($value);
      }*/

      $emailUsuarioSesion = auth()->user()->email;
      $nombrecargo = UsuariosSimple::where('email',$emailUsuarioSesion)->first()->nombre_cargo;


     if( $request->nRegistro != null ) {
        $requestNRegistro = $request->nRegistro;
      }
        if($request->areaRemtiente != null ) {
        $areRemitenteView =  $request->areaRemtiente;
      }
      if($request->remitente != null ) {
        $remitenteView =  $request->remitente;
        
      }
      if($request->materia != null ) {
        $materiaView =  $request->materia;        
      }
      if($request->destinatario != null ) {
        $destinatarioView =  $request->destinatario;        
      }


      return view('oficio.oficio_colaboraciones')
      ->with('selectA' ,$selectA)
      ->with('areRemitenteView' ,$areRemitenteView)
      ->with('remitenteView' ,$remitenteView)
      ->with('materiaView' ,$materiaView)
      ->with('destinatarioView' ,$destinatarioView)
      ->with('correlativoView' ,$correlativoView)
      ->with('feDesde' ,$feDesde)
      ->with('feHasta' ,$feHasta)
      ->with('fechaInDesde' ,$fechaInDesde)
      ->with('fechaInHasta' ,$fechaInHasta)
      ->with('fechas' ,$fechas)
      ->with('requestNRegistro' , $requestNRegistro)
      ->with('listado' , $listado)
      ->with('nombrecargo', $nombrecargo)
      ->with('esAdmin', $esAdmin);


} 

public function cargarExcelDeparatamentos (){


      $array = collect(Excel::load(public_path('departamentos2.xlsx'), function($reader) {})->get());
      $arrayTransformado = [];
      $cantidad = count($array[0]);
     
      for ($i=0; $i < $cantidad; $i++) { 
        $arrayTransformado[$array[0][$i]['area']] = $array[0][$i]['area'];
       } 

     
        return (collect($arrayTransformado)->prepend('Todos', null));
      
    }

public function show(Request $request, $id){
    $segundoArray = [];
    $detalle = OficioColaboracion::where('id', $id)->first();
    


if ($detalle->lista_colaboradores){
    $stringlistacolaboradores = $detalle->lista_colaboradores;
  
    $stringt1 = substr($detalle->lista_colaboradores, 1 , strlen($detalle->lista_colaboradores)-2);
    $primerArray = explode('],[', $stringt1);

   for ($i=1; $i < (count($primerArray)-1); $i++) { 
        $segundoArray[$i] = $primerArray[$i];
   }

     $detalle->lista_colaboradores_aux = implode('<br>', $segundoArray);
}else{
    $detalle->lista_colaboradores_aux = '';
}

         return view('oficio.oficio_colaboraciones_detalle')
            ->with('detalle', $detalle);  
}


}

resources/views/oficio/oficio.blade.php
@extends('layouts.master')
@section('page-header')
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-11">
      <h1><i class="fa fa-file-text"></i> Consulta Oficios Electrónicos</h1><br>
    </div>

  </div>
</div>
@endsection
@section('after-styles-end')
@endsection
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card card-primary card-outline">
      <div class="card-header ">
        <h5 class="card-title">Filtrar Oficio Electrónico por </h5>

      </div>
      <div class="card-body">
        <div class="box-body">
          <div class="col-sm-12">

                {!! Form::open(['route' => 'OficiosFiltros', 'method' => 'post' , 'class'=>"form-horizontal"]) !!}


                  <div class="form-row">

                    <div class="col-sm-0">
                      <label for="nRegistro" class=" col-form-label">N° Trámite: </label>
                      <input type="text" class="form-control" id="nRegistro" name="nRegistro" value="{{ $requestNRegistro }}" placeholder="N° Trámite">
                    </div>

                    <div class="col-sm-2">
                      <label for="correlativo" class=" col-form-label">Correlativo:</label>
                      <input class="form-control rounded-0" id="correlativo" name="correlativo" placeholder="Correlativo" rows="3" value="{{ $correlativoView }}">
                    </div>

                    <div class="form-group   {{ $errors->has('validacion_fechas') ? 'has-error' :'' }}">
                    <div class="input-group date">
                      <div class="col">
                          <label for="FechaDesde" class=" col-form-label">Fecha Desde: </label>
                          <input type="text" class="form-control group-date" id="FechaDesde" name="FechaDesde" readonly="readonly" value="{!! date('Y-m-d', strtotime($feDesde))  !!}">
                      </div>
                    </div>
                    </div>

                    <div class="form-group   {{ $errors->has('validacion_fechas') ? 'has-error' :'' }}">
                    <div class="input-group date">
                      <div class="col">
                          <label for="FechaHasta" class=" col-form-label">Fecha Hasta: </label>
                          <input type="text" class="form-control group-date" id="FechaHasta" name="FechaHasta" readonly="readonly" value="{!! date('Y-m-d', strtotime($feHasta ))  !!}">
                      </div>
                    </div>
                    </div>

                    <div class="col-sm-2">
                      <label for="remitente" class=" col-form-label">Remitente:</label>
                      <input class="form-control rounded-0" id="remitente" name="remitente" placeholder="Remitente" rows="3">{{ $remitenteView }} </input>
                    </div>

                    <div class="col-sm-2">
                      <label for="destinatario" class=" col-form-label">Destinatario:</label>
                      <input class="form-control rounded-0" id="destinatario" name="destinatario" placeholder="destinatario" rows="3" value="{{ $destinatarioView }}">
                    </div>

                    <div class="col-sm-2">
                      <label for="materia" class=" col-form-label">Materia:</label>
                      <textarea class="form-control rounded-0" id="materia" name="materia" placeholder="Materia" rows="3">{{ $materiaView }} </textarea>
                    </div>

                  </div>
                  <button type="submit" class="btn btn-primary pull-right">Buscar</button>
                {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



@if(count($listado)>0)
<div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-danger card-outline">
            <h5 class="card-title">Listado de Trámites y sus Derivaciones</h5>

          </div>
          <!-- /.card-header -->
          <div class="card-body table-responsive p-0">
              <table class="table table-striped table-sm"  >
                <thead >
                    <tr style="background-color: #cd0b27;">
                        <th nowrap style="color:white">Fecha</th>
                        <th nowrap style="color:white">N° Trámite</th>
                        <th nowrap style="color:white">Correlativo</th>
                        <th nowrap style="color:white">Materia</th>
                        <th nowrap style="color:white">Remitente</th>
                        <th nowrap style="color:white">División Remitente</th>
                        <th nowrap style="color:white">Destinatario</th>
                        <th nowrap style="color:white">Estatus</th>
                        <th nowrap style="color:white">Distribución Externa</th>
                        <th nowrap style="color:white">Detalles</th>
                    </tr>
                </thead>
                <tbody class="panel">
                @if(count($listado)>0)
                         @foreach ($listado as $indice => $registro)
                          <tr>
                            <td nowrap>{{$registro->fecha}}</td>
                            <td nowrap>{{$registro->tramite_id}}</td>
                            @if($registro->correlativo=='')
                            <td nowrap>{{$registro->correlativo}}</td>
                            @else
                            <td nowrap>{{$registro->correlativo->correlativo}}</td>
                            @endif
                            @if($registro->reservado != 1 || $registro->remitente==$nombrecargo || $registro->destinatario==$nombrecargo)
                            <td>{!!$registro->materia!!}</td>
                            @else
                            <td>Contenido <b>Reservado</b> solicite información al Remitente.</td>
                            @endif
                            <td>{{$registro->remitente}}</td>
                            <td>{{$registro->division}}</td>
                            <td>{{$registro->destinatario}}</td>

                           @if ($registro->doc_oficio!=null && $registro->doc_oficio!=" ")
                           <td> {{$registro->estatus}} @else <td style="background-color: #cd0b27; color: white;">{{$registro->estatus}} </td>
                           @endif
                           <td>{{$registro->documento_distribuido}}</td>
                            <td>
                             <center>
                              @if($registro->reservado != 1 || $registro->remitente==$nombrecargo || $registro->destinatario==$nombrecargo)
                              <a class="btn accion btn-info accion" href="{{route('Oficiosshow',$registro->id)}}"><i class="fa fa-eye"></i></a>
                              @endif
                            </center>
                           </td>
                          </tr>
                          @endforeach
                @endif
                </tbody>
            </table>
          <br>
        </div>
      </div>
    </div>
</div>
<br>
@else
<div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-danger card-outline">
            <h5 class="card-title">Listado de Oficios Electrónicos</h5>
          </div>
          <div class="card-body table-responsive p-0">
              <center>  No se encontraron resultados.</center>
          <br>
        </div>
      </div>
    </div>
</div>
@endif






@endsection
@section('before-scripts-end')
@include('includes.scripts.script_fecha.scripts_filtro_fecha')
@stop

resources/views/oficio/oficios.blade.php
@extends('layouts.master')
@section('page-header')
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-11">
      <h1><i class="fa fa-file-text"></i> Consulta Oficios Electrónicos</h1><br>
    </div>

  </div>
</div>
@endsection
@section('after-styles-end')
@endsection
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card card-primary card-outline">
      <div class="card-header ">
        <h5 class="card-title">Filtrar Oficio Electrónico por </h5>

      </div>
      <div class="card-body">
        <div class="box-body">
          <div class="col-sm-12">

                {!! Form::open(['route' => 'OficiossFiltros', 'method' => 'post' , 'class'=>"form-horizontal"]) !!}


                  <div class="form-row">

                    <div class="col-sm-0">
                      <label for="nRegistro" class=" col-form-label">N° Trámite: </label>
                      <input type="text" class="form-control" id="nRegistro" name="nRegistro" value="{{ $requestNRegistro }}" placeholder="N° Trámite">
                    </div>

                    <div class="col-sm-2">
                      <label for="correlativo" class=" col-form-label">Correlativo:</label>
                      <input class="form-control rounded-0" id="correlativo" name="correlativo" placeholder="Correlativo" rows="3" value="{{ $correlativoView }}">
                    </div>

                    <div class="form-group   {{ $errors->has('validacion_fechas') ? 'has-error' :'' }}">
                    <div class="input-group date">
                      <div class="col">
                          <label for="FechaDesde" class=" col-form-label">Fecha Desde: </label>
                          <input type="text" class="form-control group-date" id="FechaDesde" name="FechaDesde" readonly="readonly" value="{!! date('Y-m-d', strtotime($feDesde))  !!}">
                      </div>
                    </div>
                    </div>

                    <div class="form-group   {{ $errors->has('validacion_fechas') ? 'has-error' :'' }}">
                    <div class="input-group date">
                      <div class="col">
                          <label for="FechaHasta" class=" col-form-label">Fecha Hasta: </label>
                          <input type="text" class="form-control group-date" id="FechaHasta" name="FechaHasta" readonly="readonly" value="{!! date('Y-m-d', strtotime($feHasta ))  !!}">
                      </div>
                    </div>
                    </div>

                    <div class="col-sm-2">
                      <label for="remitente" class=" col-form-label">Remitente:</label>
                      <input class="form-control rounded-0" id="remitente" name="remitente" placeholder="Remitente" rows="3">{{ $remitenteView }} </input>
                    </div>

                    <div class="col-sm-2">
                      <label for="destinatario" class=" col-form-label">Destinatario:</label>
                      <input class="form-control rounded-0" id="destinatario" name="destinatario" placeholder="destinatario" rows="3" value="{{ $destinatarioView }}">
                    </div>

                    <div class="col-sm-2">
                      <label for="materia" class=" col-form-label">Materia:</label>
                      <textarea class="form-control rounded-0" id="materia" name="materia" placeholder="Materia" rows="3">{{ $materiaView }} </textarea>
                    </div>

                  </div>
                  <button type="submit" class="btn btn-primary pull-right">Buscar</button>
                {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



@if(count($listado)>0)
<div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-danger card-outline">
            <h5 class="card-title">Listado de Trámites y sus Derivaciones</h5>

          </div>
          <!-- /.card-header -->
          <div class="card-body table-responsive p-0">
              <table class="table table-striped table-sm"  >
                <thead >
                    <tr style="background-color: #cd0b27;">
                        <th nowrap style="color:white">Fecha</th>
                        <th nowrap style="color:white">N° Trámite</th>
                        <th nowrap style="color:white">Correlativo</th>
                        <th nowrap style="color:white">Materia</th>
                        <th nowrap style="color:white">Remitente</th>
                        <th nowrap style="color:white">División Remitente</th>
                        <th nowrap style="color:white">Destinatario</th>
                        <th nowrap style="color:white">Estatus</th>
                        <th nowrap style="color:white">Distribución Externa</th>
                        <th nowrap style="color:white">Detalles</th>
                    </tr>
                </thead>
                <tbody class="panel">
                @if(count($listado)>0)
                         @foreach ($listado as $indice => $registro)
                          <tr>
                            <td nowrap>{{$registro->fecha}}</td>
                            <td nowrap>{{$registro->tramite_id}}</td>
                            <td nowrap>{{$registro->correlativo}}</td>
                            @if($registro->reservado != 1 || $registro->remitente==$nombrecargo || $registro->destinatario==$nombrecargo)
                            <td>{!!$registro->mat!!}</td>
                            @else
                            <td>Contenido <b>Reservado</b> solicite información al Remitente.</td>
                            @endif
                            <td>@if($registro->remitente)
                              {!!$registro->remitente!!}
                              @else
                              {!!$registro->de_subrogante!!}
                              @endif
                            </td>
                            <td>{{$registro->division_remitente}}</td>
                            <td>{{$registro->destinatario}}</td>

                            @if ($registro->estatus != 'Incompleto') <td> {{$registro->estatus}} @else <td style="background-color: #cd0b27; color: white;">{{$registro->estatus}} @endif</td>

                             <td>@if ($registro->estatus != 'Incompleto') Distribuido por OPA @endif</td>

                            <td>
                             <center>
                              @if($registro->reservado != 1 || $registro->remitente==$nombrecargo || $registro->destinatario==$nombrecargo || auth()->user()->hasPermission(['99-04']))
                              <a class="btn accion btn-info accion" href="{{route('Oficioshow2',$registro->tramite_id)}}"><i class="fa fa-eye"></i></a>
                              @endif
                            </center>
                           </td>
                          </tr>
                          @endforeach
                @endif
                </tbody>
            </table>
          <br>
        </div>
      </div>
    </div>
</div>
<br>
@else
<div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-danger card-outline">
            <h5 class="card-title">Listado de Oficios Electrónicos</h5>
          </div>
          <div class="card-body table-responsive p-0">
              <center>  No se encontraron resultados.</center>
          <br>
        </div>
      </div>
    </div>
</div>
@endif






@endsection
@section('before-scripts-end')
@include('includes.scripts.script_fecha.scripts_filtro_fecha')
@stop